export enum SettingKey {
  INSTANCE_ID = 'instanceId',
  BRAND_NAME = 'brandName',
  BRAND_LOGO = 'brandLogo',
  DISALLOW_SIGN_UP = 'disallowSignUp',
  DISALLOW_SPACE_CREATION = 'disallowSpaceCreation',
  DISALLOW_SPACE_INVITATION = 'disallowSpaceInvitation',
  DISALLOW_DASHBOARD = 'disallowDashboard',
  ENABLE_EMAIL_VERIFICATION = 'enableEmailVerification',
  ENABLE_WAITLIST = 'enableWaitlist',
  AI_CONFIG = 'aiConfig',
  APP_CONFIG = 'appConfig',
  NOTIFY_MAIL_TRANSPORT_CONFIG = 'notifyMailTransportConfig',
  AUTOMATION_MAIL_TRANSPORT_CONFIG = 'automationMailTransportConfig',
  ENABLE_CREDIT_REWARD = 'enableCreditReward',
  CANARY_CONFIG = 'canaryConfig',
  TRASH_CLEANUP_ENABLED_AT = 'trashCleanupEnabledAt',
}
