import type { DomainError } from '@teable/v2-core';
import { err, ok } from 'neverthrow';
import type { Result } from 'neverthrow';

import type { SchemaRuleContext } from '../context/SchemaRuleContext';
import type {
  ISchemaRule,
  SchemaRuleI18nMessage,
  SchemaRuleRepairHint,
  SchemaRuleValidationResult,
} from './ISchemaRule';

const createMessage = (
  key: string,
  fallback: string,
  values?: Readonly<Record<string, string | number | boolean>>
): SchemaRuleI18nMessage => ({
  key,
  fallback,
  values,
});

export const getRuleRepairHint = (
  rule: ISchemaRule,
  ctx: SchemaRuleContext,
  validation: SchemaRuleValidationResult,
  options?: {
    skipStatementCheck?: boolean;
  }
): Result<SchemaRuleRepairHint, DomainError> => {
  if (validation.valid) {
    return ok({
      available: false,
      mode: rule.repairMode === 'manual' ? 'manual' : 'auto',
      reason: createMessage(
        'table:table.integrity.v2.repairMeta.reason.alreadyValid',
        'The schema is already valid.'
      ),
    });
  }

  if (rule.getRepairHint) {
    const hintResult = rule.getRepairHint(ctx, validation);
    if (hintResult.isErr()) {
      return err(hintResult.error);
    }

    if (hintResult.value) {
      return ok(hintResult.value);
    }
  }

  if (rule.repairMode === 'manual') {
    return ok({
      available: false,
      mode: 'manual',
      reason: createMessage(
        'table:table.integrity.v2.repairMeta.reason.manualRule',
        'This rule requires manual repair.'
      ),
    });
  }

  if (options?.skipStatementCheck) {
    return ok({
      available: true,
      mode: 'auto',
    });
  }

  const statementsResult = rule.up(ctx);
  if (statementsResult.isErr()) {
    return ok({
      available: false,
      mode: 'manual',
      reason: createMessage(
        'table:table.integrity.v2.repairMeta.reason.statementGenerationFailed',
        'Repair statements could not be generated.'
      ),
      description: {
        fallback: statementsResult.error.message,
      },
    });
  }

  if (statementsResult.value.length === 0) {
    return ok({
      available: false,
      mode: 'manual',
      reason: createMessage(
        'table:table.integrity.v2.repairMeta.reason.noStatements',
        'No automatic repair statements are available.'
      ),
    });
  }

  return ok({
    available: true,
    mode: 'auto',
    description: createMessage(
      'table:table.integrity.v2.repairMeta.description.autoRule',
      'The repair will execute the schema statements generated by this rule, then re-check the rule to confirm the schema is valid.'
    ),
  });
};
