import { ApiProperty } from '@nestjs/swagger';
import type { ITableVo } from '@teable-group/core';
import { FieldVo } from '../field/model/field.vo';
import { CreateRecordsVo } from '../record/open-api/record.vo';
import { ViewVo } from '../view/model/view.vo';
import { CreateTableRo } from './create-table.ro';

export class TableVo extends CreateTableRo implements ITableVo {
  @ApiProperty({
    description: 'The id of table.',
    example: 'tblxxxxxxx',
  })
  id!: string;

  @ApiProperty({
    description: 'The order of the table.',
  })
  order!: number;

  @ApiProperty({
    description:
      'The fields of the table. If it is empty, 3 fields include SingleLineText, Number, SingleSelect will be generated by default.',
    isArray: true,
    type: FieldVo,
  })
  fields!: FieldVo[];

  @ApiProperty({
    description:
      'The views of the table. If it is empty, a grid view will be generated by default.',
    isArray: true,
    type: ViewVo,
  })
  views!: ViewVo[];

  @ApiProperty({
    description:
      'The record data of the table. If it is empty, 3 empty records will be generated by default.',
    type: CreateRecordsVo,
  })
  data!: CreateRecordsVo;
}
