import type { Result } from 'neverthrow';

import type { BaseId } from '../domain/base/BaseId';
import type { DomainError } from '../domain/shared/DomainError';
import type { ISpecification } from '../domain/shared/specification/ISpecification';
import type { Field } from '../domain/table/fields/Field';
import type { LinkForeignTableReference } from '../domain/table/fields/visitors/LinkForeignTableReferenceVisitor';
import type { ITableSpecVisitor } from '../domain/table/specs/ITableSpecVisitor';
import type { Table } from '../domain/table/Table';
import type { TableId } from '../domain/table/TableId';

/**
 * Interface for update field specifications.
 * Each field type has its own UpdateXFieldSpec class that implements this interface.
 *
 * The key design decisions:
 * 1. Avoid circular references: Update logic is in separate spec classes, not in Field classes
 * 2. Fine-grained specs: Each property change generates its own spec (e.g., UpdateFormulaExpressionSpec)
 * 3. Value object comparison: Specs are generated by comparing value objects
 */
export interface IUpdateTableFieldSpec {
  /**
   * Compare current field with update input, generate fine-grained change specs.
   * Each changed property generates its own spec type.
   *
   * @param currentField - The existing field to compare against
   * @returns Array of specs for each changed property
   */
  buildSpecs(
    currentField: Field
  ): Result<ReadonlyArray<ISpecification<Table, ITableSpecVisitor>>, DomainError>;

  /**
   * Create a new field instance.
   * Only needed for type conversion.
   *
   * @param params - Optional parameters like baseId and tableId for link fields
   */
  createField(params?: { baseId?: BaseId; tableId?: TableId }): Result<Field, DomainError>;

  /**
   * Check if this update involves type conversion.
   * When true, the handler should use the multi-stage conversion flow.
   */
  isTypeConversion(): boolean;

  /**
   * Get foreign table references for the new field configuration.
   * Used to validate that referenced tables exist.
   */
  foreignTableReferences(): Result<ReadonlyArray<LinkForeignTableReference>, DomainError>;
}
