export enum FieldType {
  SingleLineText = 'SINGLE_LINE_TEXT',
  LongText = 'LONG_TEXT',
  User = 'USER',
  Attachment = 'ATTACHMENT',
  Checkbox = 'CHECKBOX',
  MultipleSelect = 'MULTIPLE_SELECT',
  SingleSelect = 'SINGLE_SELECT',
  Date = 'DATE',
  PhoneNumber = 'PHONE_NUMBER',
  Email = 'EMAIL',
  URL = 'URL',
  Number = 'NUMBER',
  Currency = 'CURRENCY',
  Percent = 'PERCENT',
  Duration = 'DURATION',
  Rating = 'RATING',
  Formula = 'FORMULA',
  Rollup = 'ROLLUP',
  Count = 'COUNT',
  Lookup = 'LOOKUP',
  CreatedTime = 'CREATED_TIME',
  LastModifiedTime = 'LAST_MODIFIED_TIME',
  CreatedBy = 'CREATED_BY',
  LastModifiedBy = 'LAST_MODIFIED_BY',
  Autonumber = 'AUTONUMBER',
  Button = 'BUTTON',
}
