services:
  integration-test:
    container_name: integration-test
    build:
      context: ../
      dockerfile: ./dockers/teable/Dockerfile
      target: builder
      args:
        INTEGRATION_TEST: 1
    hostname: integration-test
    networks:
      - teable-net
    environment:
      - PRISMA_DATABASE_URL=postgresql://teable:teable@teable-postgres:5432/teable?schema=public&statement_cache_size=1
