import type { Result } from 'neverthrow';

import type { DomainError } from '../../../shared/DomainError';
import type { AttachmentField } from '../types/AttachmentField';
import type { AutoNumberField } from '../types/AutoNumberField';
import type { ButtonField } from '../types/ButtonField';
import type { CheckboxField } from '../types/CheckboxField';
import type { ConditionalLookupField } from '../types/ConditionalLookupField';
import type { ConditionalRollupField } from '../types/ConditionalRollupField';
import type { CreatedByField } from '../types/CreatedByField';
import type { CreatedTimeField } from '../types/CreatedTimeField';
import type { DateField } from '../types/DateField';
import type { FormulaField } from '../types/FormulaField';
import type { LastModifiedByField } from '../types/LastModifiedByField';
import type { LastModifiedTimeField } from '../types/LastModifiedTimeField';
import type { LinkField } from '../types/LinkField';
import type { LongTextField } from '../types/LongTextField';
import type { LookupField } from '../types/LookupField';
import type { MultipleSelectField } from '../types/MultipleSelectField';
import type { NumberField } from '../types/NumberField';
import type { RatingField } from '../types/RatingField';
import type { RollupField } from '../types/RollupField';
import type { SingleLineTextField } from '../types/SingleLineTextField';
import type { SingleSelectField } from '../types/SingleSelectField';
import type { UserField } from '../types/UserField';

export interface IFieldVisitor<T = void> {
  visitSingleLineTextField(field: SingleLineTextField): Result<T, DomainError>;
  visitLongTextField(field: LongTextField): Result<T, DomainError>;
  visitNumberField(field: NumberField): Result<T, DomainError>;
  visitRatingField(field: RatingField): Result<T, DomainError>;
  visitFormulaField(field: FormulaField): Result<T, DomainError>;
  visitRollupField(field: RollupField): Result<T, DomainError>;
  visitSingleSelectField(field: SingleSelectField): Result<T, DomainError>;
  visitMultipleSelectField(field: MultipleSelectField): Result<T, DomainError>;
  visitCheckboxField(field: CheckboxField): Result<T, DomainError>;
  visitAttachmentField(field: AttachmentField): Result<T, DomainError>;
  visitDateField(field: DateField): Result<T, DomainError>;
  visitCreatedTimeField(field: CreatedTimeField): Result<T, DomainError>;
  visitLastModifiedTimeField(field: LastModifiedTimeField): Result<T, DomainError>;
  visitUserField(field: UserField): Result<T, DomainError>;
  visitCreatedByField(field: CreatedByField): Result<T, DomainError>;
  visitLastModifiedByField(field: LastModifiedByField): Result<T, DomainError>;
  visitAutoNumberField(field: AutoNumberField): Result<T, DomainError>;
  visitButtonField(field: ButtonField): Result<T, DomainError>;
  visitLinkField(field: LinkField): Result<T, DomainError>;
  visitLookupField(field: LookupField): Result<T, DomainError>;
  visitConditionalRollupField(field: ConditionalRollupField): Result<T, DomainError>;
  visitConditionalLookupField(field: ConditionalLookupField): Result<T, DomainError>;
}
