apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teable.nameBuilder" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- if .Values.config.mail.host }}
  mail-host: {{ .Values.config.mail.host | quote }}
  mail-port: {{ .Values.config.mail.port | quote }}
  mail-secure: {{ .Values.config.mail.secure | quote }}
  mail-sender: {{ .Values.config.mail.sender | quote }}
  mail-sender-name: {{ .Values.config.mail.senderName | quote }}
  mail-auth-username: {{ .Values.config.mail.auth.username | quote }}
  {{- end}}

  storage-provider: {{ .Values.config.storage.provider | default "minio" | quote }}
