export const v2CoreTokens = {
  tableRepository: Symbol('v2.core.tableRepository'),
  tableRecordQueryRepository: Symbol('v2.core.tableRecordQueryRepository'),
  tableRecordRepository: Symbol('v2.core.tableRecordRepository'),
  tableSchemaRepository: Symbol('v2.core.tableSchemaRepository'),
  tableUpdateFlow: Symbol('v2.core.tableUpdateFlow'),
  fieldCreationSideEffectService: Symbol('v2.core.fieldCreationSideEffectService'),
  fieldDeletionSideEffectService: Symbol('v2.core.fieldDeletionSideEffectService'),
  foreignTableLoaderService: Symbol('v2.core.foreignTableLoaderService'),
  tableMapper: Symbol('v2.core.tableMapper'),
  commandBus: Symbol('v2.core.commandBus'),
  queryBus: Symbol('v2.core.queryBus'),
  eventBus: Symbol('v2.core.eventBus'),
  realtimeEngine: Symbol('v2.core.realtimeEngine'),
  unitOfWork: Symbol('v2.core.unitOfWork'),
  logger: Symbol('v2.core.logger'),
  tracer: Symbol('v2.core.tracer'),
} as const;
