export const COMPUTED_OUTBOX_WAKEUP_QUEUE = 'v2-computed-outbox-wakeup';
export const COMPUTED_OUTBOX_WAKEUP_JOB = 'computed-outbox-wakeup';
export const COMPUTED_OUTBOX_WAKEUP_PUBLISHER = Symbol('computedOutboxWakeupPublisher');
export const COMPUTED_OUTBOX_COMPLETED_RETENTION_COUNT = 2000;
export const COMPUTED_OUTBOX_RECENT_COMPLETED_LIMIT = 10;
export const COMPUTED_OUTBOX_RECENT_FAILED_LIMIT = 10;
export const COMPUTED_OUTBOX_ANOMALY_GROUP_SAMPLE_LIMIT = 12;
export const COMPUTED_OUTBOX_ANOMALY_FETCH_CAP = 2000;
