/* eslint-disable @typescript-eslint/naming-convention */
import { z } from '../../zod';
import type { AllActions, SpaceActions } from '../actions';
import { SpaceRole } from './space.role';

export enum BaseRole {
  Creator = SpaceRole.Creator,
  Editor = SpaceRole.Editor,
  Commenter = SpaceRole.Commenter,
  Viewer = SpaceRole.Viewer,
}

export const baseRolesSchema = z.nativeEnum(BaseRole);

type ExcludeSpaceActions<T> = T extends SpaceActions ? never : T;

export type BasePermission = ExcludeSpaceActions<AllActions>;

export const basePermissions: Record<
  BaseRole | SpaceRole.Owner,
  Record<BasePermission, boolean>
> = {
  [SpaceRole.Owner]: {
    'base|create': false,
    'base|delete': true,
    'base|read': true,
    'base|update': true,
    'base|invite_email': true,
    'base|invite_link': true,
    'base|table_import': true,
    'base|table_export': true,
    'base|authority_matrix_config': true,
    'base|db_connection': true,
    'table|create': true,
    'table|delete': true,
    'table|read': true,
    'table|update': true,
    'table|import': true,
    'table|export': true,
    'view|create': true,
    'view|delete': true,
    'view|read': true,
    'view|update': true,
    'field|create': true,
    'field|delete': true,
    'field|read': true,
    'field|update': true,
    'record|create': true,
    'record|comment': true,
    'record|delete': true,
    'record|read': true,
    'record|update': true,
    'automation|create': true,
    'automation|delete': true,
    'automation|read': true,
    'automation|update': true,
    'user|email_read': true,
  },
  [BaseRole.Creator]: {
    'base|create': false,
    'base|delete': false,
    'base|read': true,
    'base|update': false,
    'base|invite_email': true,
    'base|invite_link': true,
    'base|table_import': true,
    'base|table_export': true,
    'base|authority_matrix_config': true,
    'base|db_connection': false,
    'table|create': true,
    'table|delete': true,
    'table|read': true,
    'table|update': true,
    'table|import': true,
    'table|export': true,
    'view|create': true,
    'view|delete': true,
    'view|read': true,
    'view|update': true,
    'field|create': true,
    'field|delete': true,
    'field|read': true,
    'field|update': true,
    'record|create': true,
    'record|comment': true,
    'record|delete': true,
    'record|read': true,
    'record|update': true,
    'automation|create': true,
    'automation|delete': true,
    'automation|read': true,
    'automation|update': true,
    'user|email_read': true,
  },
  [BaseRole.Editor]: {
    'base|create': false,
    'base|delete': false,
    'base|read': true,
    'base|update': false,
    'base|invite_email': true,
    'base|invite_link': true,
    'base|table_import': true,
    'base|table_export': true,
    'base|authority_matrix_config': false,
    'base|db_connection': false,
    'table|create': false,
    'table|read': true,
    'table|delete': false,
    'table|update': false,
    'table|import': false,
    'table|export': true,
    'view|create': true,
    'view|delete': true,
    'view|read': true,
    'view|update': true,
    'field|create': false,
    'field|delete': false,
    'field|read': true,
    'field|update': false,
    'record|create': true,
    'record|comment': true,
    'record|delete': true,
    'record|read': true,
    'record|update': true,
    'automation|create': false,
    'automation|delete': false,
    'automation|read': false,
    'automation|update': false,
    'user|email_read': true,
  },
  [BaseRole.Commenter]: {
    'base|create': false,
    'base|delete': false,
    'base|read': true,
    'base|update': false,
    'base|invite_email': true,
    'base|invite_link': true,
    'base|table_import': false,
    'base|table_export': true,
    'base|authority_matrix_config': false,
    'base|db_connection': false,
    'table|create': false,
    'table|delete': false,
    'table|read': true,
    'table|update': false,
    'table|import': false,
    'table|export': true,
    'view|create': false,
    'view|delete': false,
    'view|read': true,
    'view|update': false,
    'field|create': false,
    'field|delete': false,
    'field|read': true,
    'field|update': false,
    'record|create': false,
    'record|comment': true,
    'record|delete': false,
    'record|read': true,
    'record|update': false,
    'automation|create': false,
    'automation|delete': false,
    'automation|read': false,
    'automation|update': false,
    'user|email_read': true,
  },
  [BaseRole.Viewer]: {
    'base|create': false,
    'base|delete': false,
    'base|read': true,
    'base|update': false,
    'base|invite_email': true,
    'base|invite_link': true,
    'base|table_import': false,
    'base|table_export': false,
    'base|authority_matrix_config': false,
    'base|db_connection': false,
    'table|create': false,
    'table|delete': false,
    'table|read': true,
    'table|update': false,
    'table|import': false,
    'table|export': false,
    'view|create': false,
    'view|delete': false,
    'view|read': true,
    'view|update': false,
    'field|create': false,
    'field|delete': false,
    'field|read': true,
    'field|update': false,
    'record|create': false,
    'record|comment': false,
    'record|delete': false,
    'record|read': true,
    'record|update': false,
    'automation|create': false,
    'automation|delete': false,
    'automation|read': false,
    'automation|update': false,
    'user|email_read': true,
  },
};
