/* eslint-disable @typescript-eslint/naming-convention */
import type { Action } from '../actions';

export const TemplateRolePermission: Record<Action, boolean> = {
  'base|read': true,
  'table|read': true,
  'view|read': true,
  'field|read': true,
  'record|read': true,
  'automation|read': true,
  'app|read': true,
  'space|create': false,
  'space|delete': false,
  'space|update': false,
  'space|read': false,
  'space|invite_email': false,
  'space|invite_link': false,
  'space|grant_role': false,
  'base|create': false,
  'base|delete': false,
  'base|read_all': false,
  'base|update': false,
  'base|invite_email': false,
  'base|invite_link': false,
  'base|table_import': false,
  'base|table_export': false,
  'base|authority_matrix_config': false,
  'base|db_connection': false,
  'base|query_data': true,
  'table|create': false,
  'table|delete': false,
  'table|update': false,
  'table|import': false,
  'table|export': false,
  'table|trash_read': false,
  'table|trash_update': false,
  'table|trash_reset': false,
  'table_record_history|read': false,
  'view|create': false,
  'view|delete': false,
  'view|update': false,
  'view|share': false,
  'field|create': false,
  'field|delete': false,
  'field|update': false,
  'record|create': false,
  'record|comment': false,
  'record|delete': false,
  'record|update': false,
  'record|copy': false,
  'automation|create': false,
  'automation|delete': false,
  'automation|update': false,
  'app|create': false,
  'app|delete': false,
  'app|update': false,
  'user|email_read': false,
  'instance|read': false,
  'instance|update': false,
  'enterprise|read': false,
  'enterprise|update': false,
};

export const TemplatePermissions = Object.keys(TemplateRolePermission).filter(
  (permission) => TemplateRolePermission[permission as Action]
) as Action[];
