import { inject, injectable } from '@teable/v2-di';
import { err, ok, safeTry } from 'neverthrow';
import type { Result } from 'neverthrow';

import { domainError, type DomainError } from '../../domain/shared/DomainError';
import type { IDomainEvent } from '../../domain/shared/DomainEvent';
import { AndSpec } from '../../domain/shared/specification/AndSpec';
import type { ISpecification } from '../../domain/shared/specification/ISpecification';
import type { Field } from '../../domain/table/fields/Field';
import type { FieldId } from '../../domain/table/fields/FieldId';
import {
  buildFieldFilterSyncPlan,
  type FieldFilterSyncPlan,
  hasFieldFilterSyncPlanChanges,
} from '../../domain/table/fields/filter-sync';
import {
  implementsOnTeableFieldUpdated,
  type FieldUpdateContext,
} from '../../domain/table/fields/OnTeableFieldUpdated';
import { ConditionalLookupField } from '../../domain/table/fields/types/ConditionalLookupField';
import { ConditionalRollupField } from '../../domain/table/fields/types/ConditionalRollupField';
import { FormulaField } from '../../domain/table/fields/types/FormulaField';
import { LinkField } from '../../domain/table/fields/types/LinkField';
import { LookupField } from '../../domain/table/fields/types/LookupField';
import { RollupField } from '../../domain/table/fields/types/RollupField';
import type { ITableSpecVisitor } from '../../domain/table/specs/ITableSpecVisitor';
import { TableUpdateFieldTypeSpec } from '../../domain/table/specs/TableUpdateFieldTypeSpec';
import { TableUpdateViewColumnMetaSpec } from '../../domain/table/specs/TableUpdateViewColumnMetaSpec';
import {
  TableUpdateViewQueryDefaultsSpec,
  type TableViewQueryDefaultsUpdate,
} from '../../domain/table/specs/TableUpdateViewQueryDefaultsSpec';
import { Table } from '../../domain/table/Table';
import { TableUpdateResult } from '../../domain/table/TableMutator';
import { ViewColumnMeta } from '../../domain/table/views/ViewColumnMeta';
import type { ViewId } from '../../domain/table/views/ViewId';
import { ViewQueryDefaults } from '../../domain/table/views/ViewQueryDefaults';
import type {
  RecordFilter,
  RecordFilterCondition,
  RecordFilterNode,
  RecordFilterValue,
} from '../../queries/RecordFilterDto';
import * as ExecutionContextPort from '../../ports/ExecutionContext';
import * as TableRepositoryPort from '../../ports/TableRepository';
import { v2CoreTokens } from '../../ports/tokens';
import { TraceSpan } from '../../ports/TraceSpan';
import { FieldCreationSideEffectVisitor } from '../../domain/table/fields/visitors/FieldCreationSideEffectVisitor';
import { FieldDeletionSideEffectVisitor } from '../../domain/table/fields/visitors/FieldDeletionSideEffectVisitor';
import { FieldCrossTableUpdateSideEffectService } from './FieldCrossTableUpdateSideEffectService';
import { LinkFieldUpdateSideEffectService } from './LinkFieldUpdateSideEffectService';
import { TableUpdateFlow } from './TableUpdateFlow';

export type FieldUpdateSideEffectInput = {
  /** The table containing the updated field */
  table: Table;
  /** The field that was updated */
  updatedField: Field;
  /** The field before update, used for side effects that need previous state */
  previousField?: Field;
  /** The specs that were applied to update the field */
  updateSpecs: ReadonlyArray<ISpecification<Table, ITableSpecVisitor>>;
  /** Foreign tables that might be needed by dependent fields */
  foreignTables: ReadonlyArray<Table>;
};

export type FieldUpdateSideEffectResult = {
  /** All specs generated by dependent fields (including cascaded specs) */
  specs: ReadonlyArray<ISpecification<Table, ITableSpecVisitor>>;
  /** The table after all side effects have been applied */
  updatedTable: Table;
  /** Events generated during side effect processing */
  events: ReadonlyArray<IDomainEvent>;
};

@injectable()
/**
 * Application service: coordinates all field-update side effects.
 *
 * This service automatically inspects update specs and applies:
 * 1) link symmetric field side effects (oneWay/twoWay changes)
 * 2) in-table dependency cascades via `onDependencyUpdated`
 * 3) cross-table side effects (e.g. cleaning invalid link filters)
 *
 * The service processes dependents in topological order to ensure that
 * cascading updates flow correctly (e.g., formula → lookup → another lookup).
 *
 * Domain logic lives in specs/value objects/visitors; this class orchestrates
 * the execution order and persistence.
 */
export class FieldUpdateSideEffectService {
  constructor(
    @inject(v2CoreTokens.tableUpdateFlow)
    private readonly tableUpdateFlow: TableUpdateFlow,
    @inject(v2CoreTokens.tableRepository)
    private readonly tableRepository: TableRepositoryPort.ITableRepository,
    @inject(v2CoreTokens.linkFieldUpdateSideEffectService)
    private readonly linkFieldUpdateSideEffectService: LinkFieldUpdateSideEffectService,
    @inject(v2CoreTokens.fieldCrossTableUpdateSideEffectService)
    private readonly fieldCrossTableUpdateSideEffectService: FieldCrossTableUpdateSideEffectService
  ) {}

  @TraceSpan()
  async prepare(
    context: ExecutionContextPort.IExecutionContext,
    input: FieldUpdateSideEffectInput
  ): Promise<Result<ReadonlyArray<IDomainEvent>, DomainError>> {
    const service = this;
    return await safeTry<ReadonlyArray<IDomainEvent>, DomainError>(async function* () {
      const { table, updatedField, previousField, foreignTables } = input;
      if (!(updatedField instanceof LinkField) || previousField instanceof LinkField) {
        return ok([]);
      }
      if (updatedField.isOneWay()) {
        return ok([]);
      }

      const creationSideEffects = yield* FieldCreationSideEffectVisitor.collect([updatedField], {
        table,
        foreignTables,
      });
      if (creationSideEffects.length === 0) {
        return ok([]);
      }

      const events: IDomainEvent[] = [];
      for (const sideEffect of creationSideEffects) {
        const updateResult = yield* await service.tableUpdateFlow.execute(
          context,
          { table: sideEffect.foreignTable },
          (candidate) =>
            sideEffect.mutateSpec
              .mutate(candidate)
              .map((updated) => TableUpdateResult.create(updated, sideEffect.mutateSpec)),
          { publishEvents: false }
        );
        events.push(...updateResult.events);
      }

      return ok(events);
    });
  }

  @TraceSpan()
  async execute(
    context: ExecutionContextPort.IExecutionContext,
    input: FieldUpdateSideEffectInput
  ): Promise<Result<FieldUpdateSideEffectResult, DomainError>> {
    const service = this;
    return await safeTry<FieldUpdateSideEffectResult, DomainError>(async function* () {
      const { table, updatedField, updateSpecs, foreignTables } = input;

      if (updateSpecs.length === 0) {
        return ok({ specs: [], updatedTable: table, events: [] });
      }

      const events: IDomainEvent[] = [];
      const currentForeignTables = yield* await service.resolveForeignTablesForExecution(
        context,
        table,
        foreignTables,
        updatedField,
        input.previousField
      );

      // Side effect #1: link symmetric field changes (oneWay <-> twoWay)
      if (updatedField instanceof LinkField && input.previousField instanceof LinkField) {
        const linkSideEffectResult = yield* await service.linkFieldUpdateSideEffectService.execute(
          context,
          {
            table,
            updatedField,
            updateSpecs,
            foreignTables: currentForeignTables,
            previousConfig: input.previousField.config(),
          }
        );
        events.push(...linkSideEffectResult.events);
      }

      // Side effect #1a: non-link → link conversion (create symmetric field on foreign table)
      if (updatedField instanceof LinkField && !(input.previousField instanceof LinkField)) {
        const creationSideEffects = yield* FieldCreationSideEffectVisitor.collect([updatedField], {
          table,
          foreignTables: currentForeignTables,
        });
        for (const sideEffect of creationSideEffects) {
          const updateResult = yield* await service.tableUpdateFlow.execute(
            context,
            { table: sideEffect.foreignTable },
            (candidate) =>
              sideEffect.mutateSpec
                .mutate(candidate)
                .map((updated) => TableUpdateResult.create(updated, sideEffect.mutateSpec)),
            { publishEvents: false }
          );
          events.push(...updateResult.events);
        }
      }

      // Side effect #1b: link → non-link conversion (delete symmetric field from foreign table)
      if (!(updatedField instanceof LinkField) && input.previousField instanceof LinkField) {
        const deletionSideEffects = yield* FieldDeletionSideEffectVisitor.collect(
          [input.previousField],
          { table, foreignTables: currentForeignTables }
        );
        for (const sideEffect of deletionSideEffects) {
          const updateResult = yield* await service.tableUpdateFlow.execute(
            context,
            { table: sideEffect.foreignTable },
            (candidate) =>
              sideEffect.mutateSpec
                .mutate(candidate)
                .map((updated) => TableUpdateResult.create(updated, sideEffect.mutateSpec)),
            { publishEvents: false }
          );
          events.push(...updateResult.events);
        }
      }

      // Side effect #2: in-table dependency cascade (formula/lookup/rollup)
      const dependentsResult = service.getDependentsInOrder(table, updatedField);
      if (dependentsResult.isErr()) return err(dependentsResult.error);
      const dependents = dependentsResult.value;

      const updateContext: FieldUpdateContext = {
        table,
        foreignTables: currentForeignTables,
      };

      // Process each dependent - cascade specs accumulate
      const allSpecs: ISpecification<Table, ITableSpecVisitor>[] = [];
      let currentTable = table;
      const changedFields = new Map<string, Field>([[updatedField.id().toString(), updatedField]]);

      for (const dependent of dependents) {
        if (!implementsOnTeableFieldUpdated(dependent)) continue;

        const triggerField = Array.from(changedFields.values()).find((field) =>
          service.isFieldDependentOn(dependent, field.id())
        );
        if (!triggerField) continue;

        // Call onDependencyUpdated to get response specs
        const specsResult = dependent.onDependencyUpdated(
          triggerField,
          [...updateSpecs, ...allSpecs], // Pass original + accumulated cascaded specs
          { ...updateContext, table: currentTable }
        );

        if (specsResult.isErr()) return err(specsResult.error);

        const newSpecs = specsResult.value;
        if (newSpecs.length === 0) continue;

        // Apply specs to table for cascading
        for (const spec of newSpecs) {
          const mutateResult = spec.mutate(currentTable);
          if (mutateResult.isErr()) return err(mutateResult.error);
          currentTable = mutateResult.value;
          if (spec instanceof TableUpdateFieldTypeSpec) {
            changedFields.set(spec.newField().id().toString(), spec.newField());
          }
        }

        // Persist changes via TableUpdateFlow
        if (newSpecs.length > 0) {
          const composedSpec = service.composeSpecs(newSpecs);
          const updateResult = yield* await service.tableUpdateFlow.execute(
            context,
            { table: currentTable },
            (t) => ok(TableUpdateResult.create(t, composedSpec)),
            { publishEvents: false }
          );
          currentTable = updateResult.table;
          events.push(...updateResult.events);
        }

        // Add new specs to accumulator for next iteration
        allSpecs.push(...newSpecs);
      }

      const viewQueryCleanupSpecsResult = service.buildViewQueryCleanupSpecs(
        currentTable,
        updatedField,
        updateSpecs
      );
      if (viewQueryCleanupSpecsResult.isErr()) return err(viewQueryCleanupSpecsResult.error);
      const viewQueryCleanupSpecs = viewQueryCleanupSpecsResult.value;

      if (viewQueryCleanupSpecs.length > 0) {
        const composedSpec = service.composeSpecs(viewQueryCleanupSpecs);
        const updateResult = yield* await service.tableUpdateFlow.execute(
          context,
          { table: currentTable },
          (table) => ok(TableUpdateResult.create(table, composedSpec)),
          { publishEvents: false }
        );
        currentTable = updateResult.table;
        events.push(...updateResult.events);
        allSpecs.push(...viewQueryCleanupSpecs);
      }

      const viewColumnMetaCleanupSpecsResult = service.buildViewColumnMetaCleanupSpecs(
        currentTable,
        updatedField,
        updateSpecs
      );
      if (viewColumnMetaCleanupSpecsResult.isErr())
        return err(viewColumnMetaCleanupSpecsResult.error);
      const viewColumnMetaCleanupSpecs = viewColumnMetaCleanupSpecsResult.value;

      if (viewColumnMetaCleanupSpecs.length > 0) {
        const composedSpec = service.composeSpecs(viewColumnMetaCleanupSpecs);
        const updateResult = yield* await service.tableUpdateFlow.execute(
          context,
          { table: currentTable },
          (table) => ok(TableUpdateResult.create(table, composedSpec)),
          { publishEvents: false }
        );
        currentTable = updateResult.table;
        events.push(...updateResult.events);
        allSpecs.push(...viewColumnMetaCleanupSpecs);
      }

      // Side effect #3: cross-table side effects (e.g., clean link filter in host tables)
      const crossTableSideEffectResult =
        yield* await service.fieldCrossTableUpdateSideEffectService.execute(context, {
          table: currentTable,
          updatedField,
          updateSpecs,
        });
      events.push(...crossTableSideEffectResult);

      return ok({
        specs: allSpecs,
        updatedTable: currentTable,
        events,
      });
    });
  }

  private async resolveForeignTablesForExecution(
    context: ExecutionContextPort.IExecutionContext,
    table: Table,
    foreignTables: ReadonlyArray<Table>,
    updatedField: Field,
    previousField?: Field
  ): Promise<Result<ReadonlyArray<Table>, DomainError>> {
    if (!(updatedField instanceof LinkField) || previousField instanceof LinkField) {
      return ok(foreignTables);
    }

    if (updatedField.isOneWay()) {
      return ok(foreignTables);
    }

    const foreignTableId = updatedField.foreignTableId();
    const knownForeign = foreignTables.find((candidate) => candidate.id().equals(foreignTableId));
    const foreignBaseId = knownForeign?.baseId() ?? table.baseId();
    const whereSpecResult = Table.specs(foreignBaseId).byId(foreignTableId).build();
    if (whereSpecResult.isErr()) {
      return err(whereSpecResult.error);
    }

    const latestForeignResult = await this.tableRepository.findOne(context, whereSpecResult.value);
    if (latestForeignResult.isErr()) {
      return err(latestForeignResult.error);
    }

    const latestForeign = latestForeignResult.value;
    return ok(
      foreignTables.map((item) => (item.id().equals(foreignTableId) ? latestForeign : item))
    );
  }

  /**
   * Get dependent fields in topological order.
   *
   * This ensures that if field A depends on B, and B depends on the updated field,
   * then B is processed before A (so A sees B's updated state).
   */
  private getDependentsInOrder(
    table: Table,
    updatedField: Field
  ): Result<ReadonlyArray<Field>, DomainError> {
    const allFields = table.getFields();
    const fieldOrderIndex = new Map<string, number>();
    const fieldMap = new Map<string, Field>();
    for (let i = 0; i < allFields.length; i++) {
      const field = allFields[i]!;
      const id = field.id().toString();
      fieldOrderIndex.set(id, i);
      fieldMap.set(id, field);
    }

    const updatedFieldId = updatedField.id();
    const updatedFieldIdText = updatedFieldId.toString();

    const reachableIds = new Set<string>();
    const queue = [updatedFieldId];

    while (queue.length > 0) {
      const currentId = queue.shift();
      if (!currentId) continue;
      for (const field of allFields) {
        const fieldId = field.id().toString();
        if (fieldId === updatedFieldIdText || reachableIds.has(fieldId)) continue;
        if (!this.isFieldDependentOn(field, currentId)) continue;
        reachableIds.add(fieldId);
        queue.push(field.id());
      }
    }

    if (reachableIds.size === 0) {
      return ok([]);
    }

    const outgoing = new Map<string, string[]>();
    const inDegree = new Map<string, number>();

    for (const fieldId of reachableIds) {
      outgoing.set(fieldId, []);
      inDegree.set(fieldId, 0);
    }

    for (const dependentId of reachableIds) {
      const dependentField = fieldMap.get(dependentId);
      if (!dependentField) continue;

      for (const candidateDependencyId of reachableIds) {
        if (candidateDependencyId === dependentId) continue;
        const dependencyField = fieldMap.get(candidateDependencyId);
        if (!dependencyField) continue;

        if (!this.isFieldDependentOn(dependentField, dependencyField.id())) continue;

        outgoing.get(candidateDependencyId)?.push(dependentId);
        inDegree.set(dependentId, (inDegree.get(dependentId) ?? 0) + 1);
      }
    }

    const ready = Array.from(reachableIds).filter((id) => (inDegree.get(id) ?? 0) === 0);
    ready.sort((a, b) => (fieldOrderIndex.get(a) ?? 0) - (fieldOrderIndex.get(b) ?? 0));

    const orderedDependents: Field[] = [];

    while (ready.length > 0) {
      const fieldId = ready.shift();
      if (!fieldId) continue;
      const field = fieldMap.get(fieldId);
      if (field) {
        orderedDependents.push(field);
      }

      const targets = outgoing.get(fieldId) ?? [];
      for (const targetId of targets) {
        const nextDegree = (inDegree.get(targetId) ?? 0) - 1;
        inDegree.set(targetId, nextDegree);
        if (nextDegree === 0) {
          ready.push(targetId);
          ready.sort((a, b) => (fieldOrderIndex.get(a) ?? 0) - (fieldOrderIndex.get(b) ?? 0));
        }
      }
    }

    if (orderedDependents.length !== reachableIds.size) {
      return err(
        domainError.invariant({
          message: 'Detected cyclic dependency while ordering field update dependents',
        })
      );
    }

    return ok(orderedDependents);
  }

  private isFieldDependentOn(field: Field, dependencyFieldId: FieldId): boolean {
    const deps = field.dependencies();
    if (deps.some((depId) => depId.equals(dependencyFieldId))) {
      return true;
    }

    if (field instanceof FormulaField) {
      const referencedFieldIds = field.expression().getReferencedFieldIds();
      if (referencedFieldIds.isOk()) {
        if (referencedFieldIds.value.some((depId) => depId.equals(dependencyFieldId))) {
          return true;
        }
      }
    }

    return this.hasImplicitFieldDependency(field, dependencyFieldId);
  }

  private hasImplicitFieldDependency(field: Field, updatedFieldId: FieldId): boolean {
    if (field instanceof LookupField) {
      if (field.linkFieldId().equals(updatedFieldId)) return true;
      return Boolean(field.lookupOptions().condition()?.referencesField(updatedFieldId));
    }

    if (field instanceof RollupField) {
      return field.linkFieldId().equals(updatedFieldId);
    }

    if (field instanceof ConditionalLookupField) {
      if (field.lookupFieldId().equals(updatedFieldId)) return true;
      return field.conditionalLookupOptions().condition().referencesField(updatedFieldId);
    }

    if (field instanceof ConditionalRollupField) {
      if (field.lookupFieldId().equals(updatedFieldId)) return true;
      return field.config().condition().referencesField(updatedFieldId);
    }

    return false;
  }

  /**
   * Compose multiple specs into a single spec using AndSpec.
   */
  private composeSpecs(
    specs: ReadonlyArray<ISpecification<Table, ITableSpecVisitor>>
  ): ISpecification<Table, ITableSpecVisitor> {
    if (specs.length === 0) {
      throw new Error('Cannot compose empty specs array');
    }
    if (specs.length === 1) {
      return specs[0]!;
    }

    let composed: ISpecification<Table, ITableSpecVisitor> = specs[0]!;
    for (let i = 1; i < specs.length; i++) {
      composed = new AndSpec<Table, ITableSpecVisitor>(composed, specs[i]!);
    }
    return composed;
  }

  private buildViewQueryCleanupSpecs(
    table: Table,
    updatedField: Field,
    updateSpecs: ReadonlyArray<ISpecification<Table, ITableSpecVisitor>>
  ): Result<ReadonlyArray<ISpecification<Table, ITableSpecVisitor>>, DomainError> {
    const plan = buildFieldFilterSyncPlan(updatedField, updateSpecs);
    if (!hasFieldFilterSyncPlanChanges(plan)) {
      return ok([]);
    }

    const updates: TableViewQueryDefaultsUpdate[] = [];

    for (const view of table.views()) {
      const queryDefaultsResult = view.queryDefaults();
      if (queryDefaultsResult.isErr()) return err(queryDefaultsResult.error);
      const currentQueryDefaults = queryDefaultsResult.value;
      const currentFilter = currentQueryDefaults.filter();
      if (currentFilter == null) continue;
      const updatedFieldId = updatedField.id().toString();
      if (!this.hasFieldReferenceInRecordFilter(currentFilter, updatedFieldId)) continue;

      const nextFilter = this.syncRecordFilterByFieldChanges(currentFilter, updatedFieldId, plan);
      if (this.isEquivalentRecordFilter(currentFilter, nextFilter)) continue;

      const nextQueryDefaultsResult = ViewQueryDefaults.rehydrate({
        ...currentQueryDefaults.toDto(),
        filter: nextFilter,
      });
      if (nextQueryDefaultsResult.isErr()) return err(nextQueryDefaultsResult.error);

      updates.push({
        viewId: view.id(),
        queryDefaults: nextQueryDefaultsResult.value,
      });
    }

    if (updates.length === 0) {
      return ok([]);
    }

    return ok([TableUpdateViewQueryDefaultsSpec.create(updates)]);
  }

  private hasFieldReferenceInRecordFilter(filter: RecordFilter, fieldId: string): boolean {
    if (filter == null) {
      return false;
    }
    return this.hasFieldReferenceInRecordFilterNode(filter, fieldId);
  }

  private hasFieldReferenceInRecordFilterNode(node: RecordFilterNode, fieldId: string): boolean {
    if ('fieldId' in node) {
      return node.fieldId === fieldId;
    }
    if ('items' in node) {
      return node.items.some((item) => this.hasFieldReferenceInRecordFilterNode(item, fieldId));
    }
    if ('not' in node) {
      return this.hasFieldReferenceInRecordFilterNode(node.not, fieldId);
    }
    return false;
  }

  private syncRecordFilterByFieldChanges(
    filter: RecordFilter,
    fieldId: string,
    plan: FieldFilterSyncPlan
  ): RecordFilter {
    if (filter == null) {
      return null;
    }

    const transformNode = (node: RecordFilterNode): RecordFilterNode | null => {
      if ('fieldId' in node) {
        if (node.fieldId !== fieldId) {
          return { ...node };
        }

        if (plan.removeReferencedFilterItems) {
          return null;
        }

        const valueResult = this.transformRecordFilterValue(
          node.value,
          plan.renamedSelectOptionValues,
          plan.removedSelectOptionValues
        );
        if (valueResult.removeItem) {
          return null;
        }

        if (!valueResult.changed) {
          return { ...node };
        }

        return {
          ...node,
          value: (valueResult.value ?? null) as RecordFilterValue,
        } as RecordFilterCondition;
      }

      if ('items' in node) {
        const nextItems = node.items
          .map((item) => transformNode(item))
          .filter((item): item is RecordFilterNode => item != null);
        if (!nextItems.length) {
          return null;
        }
        return {
          conjunction: node.conjunction,
          items: nextItems,
        };
      }

      if ('not' in node) {
        const nextNode = transformNode(node.not);
        if (nextNode == null) {
          return null;
        }
        return { not: nextNode };
      }

      return node;
    };

    const next = transformNode(filter);
    return next ?? null;
  }

  private transformRecordFilterValue(
    value: RecordFilterValue,
    renameMap: ReadonlyMap<string, string>,
    removeSet: ReadonlySet<string>
  ): { value?: RecordFilterValue; removeItem: boolean; changed: boolean } {
    if (Array.isArray(value)) {
      const nextValues = value
        .filter((entry) => !(typeof entry === 'string' && removeSet.has(entry)))
        .map((entry) => (typeof entry === 'string' ? renameMap.get(entry) ?? entry : entry));

      if (nextValues.length === 0) {
        return { removeItem: true, changed: true };
      }

      if (
        nextValues.length === value.length &&
        nextValues.every((entry, i) => entry === value[i])
      ) {
        return { value, removeItem: false, changed: false };
      }

      return { value: nextValues as RecordFilterValue, removeItem: false, changed: true };
    }

    if (typeof value === 'string') {
      if (removeSet.has(value)) {
        return { removeItem: true, changed: true };
      }
      const renamed = renameMap.get(value);
      if (renamed === undefined || renamed === value) {
        return { value, removeItem: false, changed: false };
      }
      return { value: renamed as RecordFilterValue, removeItem: false, changed: true };
    }

    return { value, removeItem: false, changed: false };
  }

  private isEquivalentRecordFilter(left: RecordFilter, right: RecordFilter): boolean {
    return JSON.stringify(left) === JSON.stringify(right);
  }

  private buildViewColumnMetaCleanupSpecs(
    table: Table,
    updatedField: Field,
    updateSpecs: ReadonlyArray<ISpecification<Table, ITableSpecVisitor>>
  ): Result<ReadonlyArray<ISpecification<Table, ITableSpecVisitor>>, DomainError> {
    const hasTypeConversion = updateSpecs.some(
      (spec) =>
        spec instanceof TableUpdateFieldTypeSpec &&
        spec.isTypeConversion() &&
        spec.oldField().id().equals(updatedField.id())
    );
    if (!hasTypeConversion) {
      return ok([]);
    }

    const updates: Array<{
      viewId: ViewId;
      fieldId: FieldId;
      columnMeta: ViewColumnMeta;
    }> = [];
    const updatedFieldId = updatedField.id().toString();

    for (const view of table.views()) {
      const columnMetaResult = view.columnMeta();
      if (columnMetaResult.isErr()) return err(columnMetaResult.error);
      const currentColumnMeta = columnMetaResult.value;
      const currentDto = currentColumnMeta.toDto();
      const entry = currentDto[updatedFieldId];
      if (!entry || entry.statisticFunc == null) {
        continue;
      }

      const nextColumnMetaResult = ViewColumnMeta.create({
        ...currentDto,
        [updatedFieldId]: {
          ...entry,
          statisticFunc: null,
        },
      });
      if (nextColumnMetaResult.isErr()) return err(nextColumnMetaResult.error);

      if (currentColumnMeta.equals(nextColumnMetaResult.value)) {
        continue;
      }

      updates.push({
        viewId: view.id(),
        fieldId: updatedField.id(),
        columnMeta: nextColumnMetaResult.value,
      });
    }

    if (!updates.length) {
      return ok([]);
    }

    return ok([TableUpdateViewColumnMetaSpec.create(updates)]);
  }
}
