import type { V1TeableDatabase } from '@teable/v2-postgres-schema';
import type { Kysely } from 'kysely';
import { sql } from 'kysely';

export const ensureV1MetaSchema = async (db: Kysely<V1TeableDatabase>): Promise<void> => {
  await db.schema
    .createTable('space')
    .ifNotExists()
    .addColumn('id', 'text', (col) => col.primaryKey())
    .addColumn('name', 'text', (col) => col.notNull())
    .addColumn('credit', 'integer')
    .addColumn('deleted_time', 'timestamptz')
    .addColumn('created_time', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('created_by', 'text', (col) => col.notNull())
    .addColumn('last_modified_by', 'text')
    .addColumn('last_modified_time', 'timestamptz')
    .addColumn('is_template', 'boolean')
    .execute();

  await db.schema
    .createTable('base')
    .ifNotExists()
    .addColumn('id', 'text', (col) => col.primaryKey())
    .addColumn('space_id', 'text', (col) => col.notNull())
    .addColumn('name', 'text', (col) => col.notNull())
    .addColumn('order', 'double precision', (col) => col.notNull())
    .addColumn('icon', 'text')
    .addColumn('schema_pass', 'text')
    .addColumn('deleted_time', 'timestamptz')
    .addColumn('created_time', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('created_by', 'text', (col) => col.notNull())
    .addColumn('last_modified_by', 'text')
    .addColumn('last_modified_time', 'timestamptz')
    .execute();

  await db.schema
    .createTable('table_meta')
    .ifNotExists()
    .addColumn('id', 'text', (col) => col.primaryKey())
    .addColumn('base_id', 'text', (col) => col.notNull())
    .addColumn('name', 'text', (col) => col.notNull())
    .addColumn('description', 'text')
    .addColumn('icon', 'text')
    .addColumn('db_table_name', 'text', (col) => col.notNull())
    .addColumn('db_view_name', 'text')
    .addColumn('version', 'integer', (col) => col.notNull())
    .addColumn('order', 'double precision', (col) => col.notNull())
    .addColumn('created_time', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('last_modified_time', 'timestamptz')
    .addColumn('deleted_time', 'timestamptz')
    .addColumn('created_by', 'text', (col) => col.notNull())
    .addColumn('last_modified_by', 'text')
    .execute();

  await db.schema
    .createTable('field')
    .ifNotExists()
    .addColumn('id', 'text', (col) => col.primaryKey())
    .addColumn('name', 'text', (col) => col.notNull())
    .addColumn('description', 'text')
    .addColumn('options', 'text')
    .addColumn('meta', 'text')
    .addColumn('ai_config', 'text')
    .addColumn('type', 'text', (col) => col.notNull())
    .addColumn('cell_value_type', 'text', (col) => col.notNull())
    .addColumn('is_multiple_cell_value', 'boolean')
    .addColumn('db_field_type', 'text', (col) => col.notNull())
    .addColumn('db_field_name', 'text', (col) => col.notNull())
    .addColumn('not_null', 'boolean')
    .addColumn('unique', 'boolean')
    .addColumn('is_primary', 'boolean')
    .addColumn('is_computed', 'boolean')
    .addColumn('is_lookup', 'boolean')
    .addColumn('is_conditional_lookup', 'boolean')
    .addColumn('is_pending', 'boolean')
    .addColumn('has_error', 'boolean')
    .addColumn('lookup_linked_field_id', 'text')
    .addColumn('lookup_options', 'text')
    .addColumn('table_id', 'text', (col) => col.notNull())
    .addColumn('order', 'double precision', (col) => col.notNull())
    .addColumn('version', 'integer', (col) => col.notNull())
    .addColumn('created_time', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('last_modified_time', 'timestamptz')
    .addColumn('deleted_time', 'timestamptz')
    .addColumn('created_by', 'text', (col) => col.notNull())
    .addColumn('last_modified_by', 'text')
    .execute();

  await db.schema
    .createTable('view')
    .ifNotExists()
    .addColumn('id', 'text', (col) => col.primaryKey())
    .addColumn('name', 'text', (col) => col.notNull())
    .addColumn('description', 'text')
    .addColumn('table_id', 'text', (col) => col.notNull())
    .addColumn('type', 'text', (col) => col.notNull())
    .addColumn('sort', 'text')
    .addColumn('filter', 'text')
    .addColumn('group', 'text')
    .addColumn('options', 'text')
    .addColumn('order', 'double precision', (col) => col.notNull())
    .addColumn('version', 'integer', (col) => col.notNull())
    .addColumn('column_meta', 'text', (col) => col.notNull())
    .addColumn('is_locked', 'boolean')
    .addColumn('enable_share', 'boolean')
    .addColumn('share_id', 'text')
    .addColumn('share_meta', 'text')
    .addColumn('created_time', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('last_modified_time', 'timestamptz')
    .addColumn('deleted_time', 'timestamptz')
    .addColumn('created_by', 'text', (col) => col.notNull())
    .addColumn('last_modified_by', 'text')
    .execute();
};
