import {
  Type,
  Hash,
  Calendar,
  CheckSquare,
  Link2,
  User,
  List,
  FileText,
  Calculator,
  Search,
  Mail,
  Phone,
  Star,
  Percent,
  DollarSign,
  Paperclip,
  ListOrdered,
  MousePointerClick,
  Clock,
  History,
  UserPlus,
  UserPen,
  type LucideIcon,
} from 'lucide-react';

// Field type to icon mapping
export const fieldTypeIcons: Record<string, LucideIcon> = {
  singleLineText: Type,
  longText: FileText,
  number: Hash,
  date: Calendar,
  createdTime: Clock,
  lastModifiedTime: History,
  checkbox: CheckSquare,
  link: Link2,
  user: User,
  createdBy: UserPlus,
  lastModifiedBy: UserPen,
  singleSelect: List,
  multipleSelect: List,
  formula: Calculator,
  rollup: Calculator,
  conditionalRollup: Calculator,
  lookup: Search,
  conditionalLookup: Search,
  email: Mail,
  phone: Phone,
  rating: Star,
  percent: Percent,
  currency: DollarSign,
  attachment: Paperclip,
  autoNumber: ListOrdered,
  button: MousePointerClick,
};

export function getFieldTypeIcon(fieldType: string): LucideIcon {
  return fieldTypeIcons[fieldType] || Type;
}
