name: Integration Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    paths:
      - 'apps/nestjs-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.9.0]
        database-type: [postgres]
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    env:
      CI: 1

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: 🧪 Run Tests
        env:
          CI: 1
          VITEST_MAX_THREADS: 2
          VITEST_MIN_THREADS: 1
          VITEST_SHARD: ${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
          VITEST_REPORTER: blob
        run: |
          make ${{ matrix.database-type }}.integration.test
      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: .vitest-reports/*
          include-hidden-files: true
          retention-days: 1
  

  finish:
    if: ${{ !cancelled() }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: run unit tests
        run: |
          pnpm -F "@teable/backend" test-unit-cover
          pnpm -F "@teable/backend" merge-cover
          pnpm -F "@teable/backend" generate-cover

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: .vitest-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge reports
        run: npx vitest --merge-reports

      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
